export default class Verbs {
  constructor(
    public id: number,
    public infinitive: string,
    public pastSimple: string[],
    public pastParticiple: string[],
    public translate: string
  ) {}
}

export const IrregularVerbs: Verbs[] = [
  new Verbs(1, "arise", ["arose"], ["arisen"], "wstać, powstać"),
  new Verbs(2, "be", ["was", "were"], ["been"], "być"),
  new Verbs(3, "bear", ["bore"], ["borne", "born"], "rodzić"),
  new Verbs(4, "beat", ["beat"], ["beaten"], "bić, uderzać"),
  new Verbs(5, "become", ["became"], ["become"], "stać się"),
  new Verbs(6, "begin", ["began"], ["begun"], "zacząć"),
  new Verbs(7, "bend", ["bent"], ["bent"], "zginąć"),
  new Verbs(8, "bite", ["bit"], ["bitten"], "gryźć"),
  new Verbs(9, "blow", ["blew"], ["blown"], "wiać, dmuchać"),
  new Verbs(10, "break", ["broke"], ["broken"], "łamać"),
  new Verbs(11, "bring", ["brought"], ["brought"], "przynieść"),
  new Verbs(12, "build", ["build"], ["built"], "budować"),
  new Verbs(
    13,
    "burn",
    ["burnt", "burned"],
    ["burnt", "burned"],
    "płonąć, palić"
  ),
  new Verbs(14, "burst", ["burst"], ["burst"], "wybuchnąć"),
  new Verbs(15, "buy", ["bought"], ["bought"], "kupić"),
  new Verbs(16, "catch", ["caught"], ["caught"], "łapać"),
  new Verbs(17, "choose", ["chose"], ["chosen"], "wybierać"),

  new Verbs(18, "come", ["came"], ["come"], "przyjść"),
  new Verbs(19, "cost", ["cost"], ["cost"], "kosztować"),
  new Verbs(20, "cut", ["cut"], ["cut"], "ciąć, kroić"),
  new Verbs(21, "do", ["did"], ["done"], "robić, czynić"),
  new Verbs(22, "draw", ["drew"], ["drawn"], "rysować, ciągnąć"),
  new Verbs(
    23,
    "dream",
    ["dreamed", "dreamt"],
    ["dreamed", "dreamt"],
    "śnić, marzyć"
  ),
  new Verbs(24, "drink", ["drank"], ["drunk"], "pić"),
  new Verbs(25, "drive", ["drove"], ["driven"], "jechać(prowadzić pojazd)"),
  new Verbs(26, "eat", ["ate"], ["eaten"], "jeść"),
  new Verbs(27, "fall", ["fell"], ["fallen"], "spaść, upaść"),
  new Verbs(28, "fell", ["felt"], ["felt"], "czuć"),
  new Verbs(29, "fight", ["fought"], ["fought"], "walczyć"),
  new Verbs(30, "find", ["found"], ["found"], "znaleźć"),
  new Verbs(31, "fly", ["flew"], ["flown"], "lecieć"),
  new Verbs(32, "forget", ["forgot"], ["forgotten"], "zapomnień"),
  new Verbs(33, "forgive", ["forgave"], ["forgiven"], "wybaczyć"),
  new Verbs(34, "freeze", ["froze"], ["frozen"], "zamarzać"),
  new Verbs(35, "get", ["got"], ["got"], "dostać"),
  new Verbs(36, "give", ["gave"], ["given"], "dać"),
  new Verbs(37, "go", ["went"], ["gone"], "iść, jechać"),
  new Verbs(38, "grow", ["grew"], ["grown"], "rosnąć"),
  new Verbs(39, "hang", ["hung"], ["hung"], "wisieć"),
  new Verbs(40, "have", ["had"], ["had"], "mieć"),
  new Verbs(41, "hear", ["heard"], ["heard"], "słyszeć"),
  new Verbs(42, "hide", ["hid"], ["hidden"], "chować, ukrywać"),
  new Verbs(43, "hit", ["hit"], ["hit"], "uderzyć"),
  new Verbs(44, "hold", ["held"], ["held"], "trzymać, przytulać"),
  new Verbs(45, "hurt", ["hurt"], ["hurt"], "kaleczyć, ranić"),
  new Verbs(46, "keep", ["kept"], ["kept"], "trzymać, zachować"),
  new Verbs(47, "know", ["knew"], ["known"], "wiedzieć, znać"),
  new Verbs(48, "lay", ["laid"], ["laid"], "kłaść"),
  new Verbs(49, "lead", ["led"], ["led"], "prowadzić"),
  new Verbs(50, "leap", ["leapt", "leaped"], ["leapt", "leaped"], "skoczyć"),
  new Verbs(
    51,
    "learn",
    ["learnt", "learned"],
    ["learnt", "learned"],
    "uczyć się"
  ),
  new Verbs(52, "lend", ["lent"], ["lent"], "pożyczać (komuś)"),
  new Verbs(53, "let", ["let"], ["let"], "pozwalać"),
  new Verbs(54, "lie", ["lay"], ["lain"], "leżeć"),
  new Verbs(55, "lose", ["lost"], ["lost"], "tracić, gubić"),
  new Verbs(56, "make", ["made"], ["made"], "robić, wykonywać"),
  new Verbs(57, "mean", ["meant"], ["meant"], "znaczyć, mieć na myśli"),
  new Verbs(58, "meet", ["met"], ["met"], "spotykać"),
  new Verbs(59, "pay", ["paid"], ["paid"], "płacić"),
  new Verbs(60, "put", ["put"], ["put"], "kłaść"),
  new Verbs(61, "read", ["read"], ["read"], "czytać"),
  new Verbs(62, "ride", ["rode"], ["ridden"], "jeździć(konno, na rowerze)"),
  new Verbs(63, "ring", ["rang"], ["rung"], "dzwonić"),
  new Verbs(64, "rise", ["rose"], ["risen"], "wstać"),
  new Verbs(65, "run", ["ran"], ["run"], "biec"),
  new Verbs(66, "say", ["said"], ["said"], "powiedzieć"),
  new Verbs(67, "see", ["saw"], ["seen"], "widzieć"),
  new Verbs(68, "sell", ["sold"], ["sold"], "srzedać"),
  new Verbs(69, "send", ["sent"], ["sent"], "posłać, wysłać"),
  new Verbs(70, "set", ["set"], ["set"], "ustawić, umieścić"),
  new Verbs(71, "shake", ["shook"], ["shaken"], "trząść"),
  new Verbs(72, "shine", ["shone"], ["shone"], "świecić, lśnić"),
  new Verbs(73, "shoot", ["shot"], ["shot"], "strzelać"),
  new Verbs(74, "show", ["showed"], ["shown"], "pokazywać"),
  new Verbs(75, "shrink", ["shrank"], ["shrunk"], "kurczyć się, maleć"),
  new Verbs(76, "shut", ["shut"], ["shut"], "zamykać"),
  new Verbs(77, "sing", ["sang"], ["sung"], "śpiewać"),
  new Verbs(78, "sit", ["sat"], ["sat"], "siadać, siedzieć"),
  new Verbs(
    79,
    "smell",
    ["smelt", "smelled"],
    ["smelt", "smelled"],
    "pachnieć, wąchać"
  ),
  new Verbs(80, "speak", ["spoke"], ["spoken"], "mówić"),
  new Verbs(81, "spend", ["spent"], ["spent"], "spędzać, wydawać"),
  new Verbs(82, "spread", ["spread"], ["spread"], "rozpościerać, rozdkładać"),
  new Verbs(83, "stand", ["stood"], ["stood"], "stać"),
  new Verbs(84, "steal", ["stole"], ["stolen"], "kraść"),
  new Verbs(85, "stick", ["stuck"], ["stuck"], "utknąć, ugrzęznąć"),
  new Verbs(86, "strike", ["struck"], ["struck"], "uderzyć"),
  new Verbs(87, "swear", ["swore"], ["sworn"], "przysięgać, przeklinać"),
  new Verbs(88, "sweep", ["swept"], ["swept"], "zamiatać"),
  new Verbs(89, "swim", ["swam"], ["swum"], "pływać"),
  new Verbs(90, "swing", ["swung"], ["swung"], "kołysać się"),
  new Verbs(91, "take", ["took"], ["taken"], "brać"),
  new Verbs(92, "teach", ["taught"], ["taught"], "uczyć"),
  new Verbs(93, "tear", ["tore"], ["torn"], "drzeć, szarpać"),
  new Verbs(94, "tell", ["told"], ["told"], "powiedzieć"),
  new Verbs(95, "think", ["thought"], ["thought"], "myśleć"),
  new Verbs(96, "throw", ["threw"], ["thrown"], "rzucać"),
  new Verbs(97, "understand", ["understood"], ["understood"], "rozumieć"),
  new Verbs(98, "wake", ["woke", "waked"], ["woken", "waked"], "budzić"),
  new Verbs(99, "wear", ["wore"], ["worn"], "mieć na sobie, nosić(o ubraniu)"),
  new Verbs(100, "win", ["won"], ["won"], "wygrać, zwyciężyć"),
  new Verbs(101, "write", ["wrote"], ["written"], "pisać"),
];
